apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyseerr-pv-local-config
  namespace: jellyseerr
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: "/mnt/kubernetes/jellyseerr-pv-local-config"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyseerr-pvc-config
  namespace: jellyseerr
spec:
  storageClassName: local-storage
  volumeName: jellyseerr-pv-local-config
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
