---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyseerr-pv-nfs-config
  namespace: jellyseerr
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-csi
  mountOptions:
    - nfsvers=3
    - nolock
  csi:
    driver: nfs.csi.k8s.io
    # volumeHandle format: {nfs-server-address}#{sub-dir-name}#{share-name}
    # make sure this value is unique for every share in the cluster
    volumeHandle: 192.168.0.110#nfs#kubernetes-jellyseerr-config
    volumeAttributes:
      server: 192.168.0.110
      share: /nfs
      subdir: kubernetes/jellyseerr-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyseerr-pvc-config
  namespace: jellyseerr
spec:
  volumeName: jellyseerr-pv-nfs-config
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi