---
kind: Service
apiVersion: v1
metadata:
  name: radarr-tcp
  namespace: radarr
spec:
  selector:
    app: radarr
  ports:
  - port: 80
    targetPort: 7878
    name: radarr-tcp
    protocol: TCP
  type: ClusterIP
