apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jellyfin
  name: jellyfin
  namespace: jellyfin
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      volumes:
      - name: jellyfin-pvc-config
        persistentVolumeClaim:
          claimName: jellyfin-pvc-config
      - name: jellyfin-pvc-data
        persistentVolumeClaim:
          claimName: jellyfin-pvc-data
      containers:
      - env:
        - name: JELLYFIN_PublishedServerUrl 
          value: jellyfin.home.neels.tech
        - name: PGID
          value: "\x36\x35\x35\x34\x31"
        - name: PUID
          value: "\x31\x30\x34\x34"
        - name: TZ
          value: Europe/Amsterdam
        securityContext:
          privileged: true # Container must run as privileged inside of the pod, required for hardware acceleration
        image: ghcr.io/linuxserver/jellyfin
        name: jellyfin
        ports:
        - containerPort: 8096
          name: http-tcp
          protocol: TCP
        - containerPort: 8920
          name: https-tcp
          protocol: TCP
        - containerPort: 1900
          name: dlna-udp
          protocol: UDP
        - containerPort: 7359
          name: discovery-udp
          protocol: UDP      
        resources: 
            requests: 
                gpu.intel.com/i915: "1" 
            limits: 
                gpu.intel.com/i915: "1" 
        stdin: true
        tty: true
        volumeMounts:
        - mountPath: /config
          name: jellyfin-pvc-config
        - mountPath: /data
          name: jellyfin-pvc-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
