apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-pv-nfs-config
  namespace: jellyfin
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=3
  csi:
    driver: nfs.csi.k8s.io
    # volumeHandle format: {nfs-server-address}#{sub-dir-name}#{share-name}
    # make sure this value is unique for every share in the cluster
    volumeHandle: $NFS_SERVER_IP#nfs#jellyfin-config
    volumeAttributes:
      server: $NFS_SERVER_IP
      share: /nfs
      subdir: jellyfin-config
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-pv-nfs-data
  namespace: jellyfin
spec:
  capacity:
    storage: 4Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=3
  csi:
    driver: nfs.csi.k8s.io
    # volumeHandle format: {nfs-server-address}#{sub-dir-name}#{share-name}
    # make sure this value is unique for every share in the cluster
    volumeHandle: $NFS_SERVER_IP#nfs#jellyfin-data
    volumeAttributes:
      server: $NFS_SERVER_IP
      share: /nfs
      subdir: jellyfin-data