apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: media
    app.kubernetes.io/name: jellyfin
    app.kubernetes.io/part-of: jellyfin
  name: jellyfin
  namespace: jellyfin
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8096
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8920
  - name: dlna
    port: 1900
    protocol: UDP
    targetPort: 1900
  - name: discovery
    port: 7359
    protocol: UDP
    targetPort: 7359
