apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-credentials
  namespace: default
  annotations:
   reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
   reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
type: Opaque
stringData:
  email: $CLOUDFLARE_API_EMAIL
  api-key: $CLOUDFLARE_API_KEY
---
apiVersion: v1
kind: Secret
metadata:
  name: tunnel-credentials
  namespace: cloudflared
type: Opaque
data:
  credentials.json: "$CLOUDFLARED_JSON_CREDS_BASE64"
