apiVersion: v1
kind: Secret
metadata:
  name: tailscale-postgresql
  namespace: default
  annotations:
   reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
   reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
type: Opaque
stringData:
  password: $POSTGRES_PASSWORD
