apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: device-plugin-operator
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
  project: default
  source:
    chart: intel-device-plugins-operator
    repoURL: https://intel.github.io/helm-charts/
    targetRevision: 0.29.0
    helm:
      releaseName: device-plugin-operator
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gpu-device-plugin
  namespace: argocd
spec:
  syncPolicy:
    automated:
      prune: true
  project: default
  source:
    chart: intel-device-plugins-gpu
    repoURL: https://intel.github.io/helm-charts/
    targetRevision: 0.29.0
    helm:
      releaseName: gpu-device-plugin
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
