apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik-home-neels-tech-tls
spec:
  secretName: traefik-home-neels-tech-tls
  issuerRef:
    name: star-home-neels-tech-issuer
    kind: ClusterIssuer
  dnsNames:
    - traefik.home.neels.tech
