---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: home-assistant-pv-nfs-config
  namespace: home-assistant
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-csi
  mountOptions:
    - nfsvers=3
    - nolock
  csi:
    driver: nfs.csi.k8s.io
    # volumeHandle format: {nfs-server-address}#{sub-dir-name}#{share-name}
    # make sure this value is unique for every share in the cluster
    volumeHandle: 192.168.0.110#nfs#kubernetes-home-assistant-config
    volumeAttributes:
      server: 192.168.0.110
      share: /nfs
      subdir: kubernetes/home-assistant-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-pvc-config
  namespace: home-assistant
spec:
  volumeName: home-assistant-pv-nfs-config
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mosquitto-pv-nfs-config
  namespace: home-assistant
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-csi
  mountOptions:
    - nfsvers=3
    - nolock
  csi:
    driver: nfs.csi.k8s.io
    # volumeHandle format: {nfs-server-address}#{sub-dir-name}#{share-name}
    # make sure this value is unique for every share in the cluster
    volumeHandle: 192.168.0.110#nfs#kubernetes-mosquitto-config
    volumeAttributes:
      server: 192.168.0.110
      share: /nfs
      subdir: kubernetes/mosquitto-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto-pvc-config
  namespace: home-assistant
spec:
  volumeName: mosquitto-pv-nfs-config
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zigbee2mqtt-pv-nfs-data
  namespace: home-assistant
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-csi
  mountOptions:
    - nfsvers=3
    - nolock
  csi:
    driver: nfs.csi.k8s.io
    # volumeHandle format: {nfs-server-address}#{sub-dir-name}#{share-name}
    # make sure this value is unique for every share in the cluster
    volumeHandle: 192.168.0.110#nfs#kubernetes-zigbee2mqtt-data
    volumeAttributes:
      server: 192.168.0.110
      share: /nfs
      subdir: kubernetes/zigbee2mqtt-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zigbee2mqtt-pvc-data
  namespace: home-assistant
spec:
  volumeName: zigbee2mqtt-pv-nfs-data
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
