apiVersion: v1
kind: Service
metadata:
  namespace: home-assistant
  name: home-assistant-http
spec:
  selector:
    app: home-assistant
  type: ClusterIP
  ports:
  - name: home-assistant-http
    protocol: TCP
    port: 80
    targetPort: 8123
---
apiVersion: v1
kind: Service
metadata:
  namespace: home-assistant
  name: zigbee2mqtt-http
spec:
  selector:
    app: zigbee2mqtt
  type: ClusterIP
  ports:
  - name: zigbee2mqtt-http
    protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  namespace: home-assistant
  name: mosquitto-tcp
spec:
  selector:
    app: mosquitto
  type: ClusterIP
  ports:
  - name: mqtt0
    protocol: TCP
    port: 1883
    targetPort: 1883
  - name: mqtt1
    protocol: TCP
    port: 9001
    targetPort: 9001        
