apiVersion: v1
kind: PersistentVolume
metadata:
  name: prowlarr-pv-local-config
  namespace: prowlarr
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: "/mnt/kubernetes/prowlarr-pv-local-config"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-pvc-config
  namespace: prowlarr
spec:
  volumeName: prowlarr-pv-local-config
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi