apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prowlarr
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
  project: default
  source:
    repoURL: https://github.com/Neels-v-Wyk/home-neels-tech.git
    targetRevision: HEAD
    path: kubernetes/argocd/prowlarr
  destination:
    server: https://kubernetes.default.svc
    namespace: prowlarr
