apiVersion: v1
kind: Secret
metadata:
  name: tunnel-credentials
  namespace: cloudflared
type: Opaque
stringData:
  credentials.json: $CLOUDFLARED_JSON_CREDS_CONTENTS
---
apiVersion: v1
kind: Secret
metadata:
  name: tunnel-pem
  namespace: cloudflared
type: Opaque
stringData:
  credentials.json: $CLOUDFLARED_PEM_CONTENTS
