apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-pv-local-config
  namespace: sonarr
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: "/mnt/kubernetes/sonarr-pv-local-config"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-pvc-config
  namespace: sonarr
spec:
  volumeName: sonarr-pv-local-config
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-pv-nfs-data
  namespace: sonarr
spec:
  capacity:
    storage: 2Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-csi
  mountOptions:
    - nfsvers=3
    - nolock
  csi:
    driver: nfs.csi.k8s.io
    # volumeHandle format: {nfs-server-address}#{sub-dir-name}#{share-name}
    # make sure this value is unique for every share in the cluster
    volumeHandle: 192.168.0.110#nfs#kubernetes-sonarr-data
    volumeAttributes:
      server: 192.168.0.110
      share: /nfs
      subdir: kubernetes/jellyfin-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-pvc-data
  namespace: sonarr
spec:
  volumeName: sonarr-pv-nfs-data
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Ti
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-pv-nfs-downloads
  namespace: sonarr
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-csi
  mountOptions:
    - nfsvers=3
    - nolock
  csi:
    driver: nfs.csi.k8s.io
    # volumeHandle format: {nfs-server-address}#{sub-dir-name}#{share-name}
    # make sure this value is unique for every share in the cluster
    volumeHandle: 192.168.0.110#nfs#kubernetes-sonarr-downloads
    volumeAttributes:
      server: 192.168.0.110
      share: /nfs
      subdir: kubernetes/qbittorrent-data/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-pvc-downloads
  namespace: sonarr
spec:
  volumeName: sonarr-pv-nfs-downloads
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi