---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrent-pv-nfs-config
  namespace: qbittorrent
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-csi
  mountOptions:
    - nfsvers=3
    - nolock
  csi:
    driver: nfs.csi.k8s.io
    # volumeHandle format: {nfs-server-address}#{sub-dir-name}#{share-name}
    # make sure this value is unique for every share in the cluster
    volumeHandle: 192.168.0.110#nfs#kubernetes-qbittorrent-config
    volumeAttributes:
      server: 192.168.0.110
      share: /nfs
      subdir: kubernetes/qbittorrent-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-pvc-config
  namespace: qbittorrent
spec:
  volumeName: qbittorrent-pv-nfs-config
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrent-pv-nfs-data
  namespace: qbittorrent
spec:
  capacity:
    storage: 2Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-csi
  mountOptions:
    - nfsvers=3
    - nolock
  csi:
    driver: nfs.csi.k8s.io
    # volumeHandle format: {nfs-server-address}#{sub-dir-name}#{share-name}
    # make sure this value is unique for every share in the cluster
    volumeHandle: 192.168.0.110#nfs#kubernetes-qbittorrent-data
    volumeAttributes:
      server: 192.168.0.110
      share: /nfs
      subdir: kubernetes/jellyfin-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-pvc-data
  namespace: qbittorrent
spec:
  volumeName: qbittorrent-pv-nfs-data
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Ti